import { z } from "zod";

import {
  autocompleteRequestSchema,
  autocompleteResponseSchema,
  type AutocompleteRequest,
  type AutocompleteResponse,
} from "./autocomplete";
import {
  googlePropertySchema,
  resolutionSchema,
  topicSchema,
  exploreWidgetSchema,
  type ExploreWidget,
  type GoogleProperty,
  type Resolution,
  type Topic,
} from "./common";
import {
  dailyTrendsRequestSchema,
  dailyTrendsResponseSchema,
  dailyTrendItemSchema,
  dailyTrendArticleSchema,
  type DailyTrendsRequest,
  type DailyTrendsResponse,
  type DailyTrendItem,
  type DailyTrendArticle,
} from "./daily-trends";
import {
  hotTrendsLegacyRequestSchema,
  hotTrendsLegacyResponseSchema,
  type HotTrendsLegacyRequest,
  type HotTrendsLegacyResponse,
} from "./experimental-hot-trends-legacy";
import {
  pickerRequestSchema,
  geoPickerResponseSchema,
  categoryPickerResponseSchema,
  pickerNodeSchema,
  type GeoPickerRequest,
  type CategoryPickerRequest,
  type GeoPickerResponse,
  type CategoryPickerResponse,
  type PickerNode,
} from "./experimental-pickers";
import {
  trendingArticlesRequestSchema,
  trendingArticleItemSchema,
  trendingArticlesResponseSchema,
  type TrendingArticlesRequest,
  type TrendingArticleItem,
  type TrendingArticlesResponse,
} from "./experimental-trending-articles";
import {
  articleKeySchema,
  trendingNowRequestSchema,
  trendingNowItemSchema,
  trendingNowResponseSchema,
  type ArticleKey,
  type TrendingNowRequest,
  type TrendingNowItem,
  type TrendingNowResponse,
} from "./experimental-trending-now";
import {
  exploreRequestSchema,
  exploreResponseSchema,
  type ExploreRequest,
  type ExploreResponse,
} from "./explore";
import {
  interestByRegionRequestSchema,
  interestByRegionResponseSchema,
  geoMapDataSchema,
  type InterestByRegionRequest,
  type InterestByRegionResponse,
  type GeoMapData,
} from "./interest-by-region";
import {
  interestOverTimeRequestSchema,
  interestOverTimeResponseSchema,
  interestOverTimePointSchema,
  type InterestOverTimeRequest,
  type InterestOverTimeResponse,
  type InterestOverTimePoint,
} from "./interest-over-time";
import {
  interestOverTimeMultirangeRequestSchema,
  interestOverTimeMultirangeResponseSchema,
  multirangeColumnDataSchema,
  interestOverTimeMultirangePointSchema,
  type InterestOverTimeMultirangeRequest,
  type InterestOverTimeMultirangeResponse,
  type InterestOverTimeMultirangePoint,
  type MultirangeColumnData,
} from "./interest-over-time-multirange";
import {
  realTimeTrendsRequestSchema,
  realTimeTrendsResponseSchema,
  realTimeStorySchema,
  type RealTimeTrendsRequest,
  type RealTimeTrendsResponse,
  type RealTimeStory,
} from "./real-time-trends";
import {
  relatedQueriesRequestSchema,
  relatedQueriesResponseSchema,
  relatedQueryItemSchema,
  type RelatedQueriesRequest,
  type RelatedQueriesResponse,
  type RelatedQueryItem,
} from "./related-queries";
import {
  relatedTopicsRequestSchema,
  relatedTopicsResponseSchema,
  relatedTopicItemSchema,
  type RelatedTopicsRequest,
  type RelatedTopicsResponse,
  type RelatedTopicItem,
} from "./related-topics";
import {
  topChartsRequestSchema,
  topChartsResponseSchema,
  topChartListItemSchema,
  topChartSchema,
  type TopChartsRequest,
  type TopChartsResponse,
  type TopChart,
  type TopChartListItem,
} from "./top-charts";

export {
  autocompleteRequestSchema,
  autocompleteResponseSchema,
  articleKeySchema,
  categoryPickerResponseSchema,
  dailyTrendArticleSchema,
  dailyTrendItemSchema,
  dailyTrendsRequestSchema,
  dailyTrendsResponseSchema,
  exploreRequestSchema,
  exploreResponseSchema,
  exploreWidgetSchema,
  geoMapDataSchema,
  geoPickerResponseSchema,
  googlePropertySchema,
  hotTrendsLegacyRequestSchema,
  hotTrendsLegacyResponseSchema,
  interestByRegionRequestSchema,
  interestByRegionResponseSchema,
  interestOverTimePointSchema,
  interestOverTimeRequestSchema,
  interestOverTimeResponseSchema,
  interestOverTimeMultirangePointSchema,
  interestOverTimeMultirangeRequestSchema,
  interestOverTimeMultirangeResponseSchema,
  multirangeColumnDataSchema,
  pickerNodeSchema,
  pickerRequestSchema,
  realTimeStorySchema,
  realTimeTrendsRequestSchema,
  realTimeTrendsResponseSchema,
  relatedQueriesRequestSchema,
  relatedQueriesResponseSchema,
  relatedQueryItemSchema,
  relatedTopicItemSchema,
  relatedTopicsRequestSchema,
  relatedTopicsResponseSchema,
  resolutionSchema,
  topicSchema,
  topChartListItemSchema,
  topChartSchema,
  topChartsRequestSchema,
  topChartsResponseSchema,
  trendingArticleItemSchema,
  trendingArticlesRequestSchema,
  trendingArticlesResponseSchema,
  trendingNowItemSchema,
  trendingNowRequestSchema,
  trendingNowResponseSchema,
  z,
};

export type {
  ArticleKey,
  AutocompleteRequest,
  AutocompleteResponse,
  CategoryPickerRequest,
  CategoryPickerResponse,
  DailyTrendArticle,
  DailyTrendItem,
  DailyTrendsRequest,
  DailyTrendsResponse,
  ExploreRequest,
  ExploreResponse,
  ExploreWidget,
  GeoMapData,
  GeoPickerRequest,
  GeoPickerResponse,
  GoogleProperty,
  HotTrendsLegacyRequest,
  HotTrendsLegacyResponse,
  InterestByRegionRequest,
  InterestByRegionResponse,
  InterestOverTimePoint,
  InterestOverTimeRequest,
  InterestOverTimeResponse,
  InterestOverTimeMultirangePoint,
  InterestOverTimeMultirangeRequest,
  InterestOverTimeMultirangeResponse,
  MultirangeColumnData,
  PickerNode,
  RealTimeStory,
  RealTimeTrendsRequest,
  RealTimeTrendsResponse,
  RelatedQueriesRequest,
  RelatedQueriesResponse,
  RelatedQueryItem,
  RelatedTopicItem,
  RelatedTopicsRequest,
  RelatedTopicsResponse,
  Resolution,
  TopChart,
  TopChartListItem,
  TopChartsRequest,
  TopChartsResponse,
  Topic,
  TrendingArticleItem,
  TrendingArticlesRequest,
  TrendingArticlesResponse,
  TrendingNowItem,
  TrendingNowRequest,
  TrendingNowResponse,
};

export const schemas = {
  z,
  autocompleteRequestSchema,
  autocompleteResponseSchema,
  exploreRequestSchema,
  exploreResponseSchema,
  interestOverTimeRequestSchema,
  interestOverTimeResponseSchema,
  interestByRegionRequestSchema,
  interestByRegionResponseSchema,
  relatedQueriesRequestSchema,
  relatedQueriesResponseSchema,
  relatedTopicsRequestSchema,
  relatedTopicsResponseSchema,
  dailyTrendsRequestSchema,
  dailyTrendsResponseSchema,
  realTimeTrendsRequestSchema,
  realTimeTrendsResponseSchema,
  topChartsRequestSchema,
  topChartsResponseSchema,
  interestOverTimeMultirangeRequestSchema,
  interestOverTimeMultirangeResponseSchema,
  hotTrendsLegacyRequestSchema,
  hotTrendsLegacyResponseSchema,
  trendingNowRequestSchema,
  trendingNowResponseSchema,
  trendingArticlesRequestSchema,
  trendingArticlesResponseSchema,
  geoPickerResponseSchema,
  categoryPickerResponseSchema,
  resolutionSchema,
  googlePropertySchema,
  topicSchema,
};
